
pub enum TelnetOptionType {
    TransmitBinary = 0,
    Echo = 1,
    Reconnection = 2,
    SuppressGoAhead = 3,
    ApproxMessageSizeNeg = 4,
    Status = 5,
    TimingMark = 6,
    RCTE = 7,
    OutLineWidth = 8,
    OutPageSize = 9,
    NAOCRD = 10,
    NAOHTS = 11,
    NAOHTD = 12,
    NAOFFD = 13,
    NAOVTS = 14,
    NAOVTD = 15,
    NAOLFD = 16,
    XASCII = 17,
    Logout = 18,
    ByteMacro = 19,
    DET = 20,
    SUPDUP = 21,
    SUPDUPOutput = 22,
    SNDLOC = 23,
    TTYPE = 24,
    EOR = 25,
    TUID = 26,
    OUTMRK = 27,
    TTYLOC = 28,
    OPT3270Regime = 29,
    X3PAD = 30,
    NAWS = 31,
    TSPEED = 32,
    LFLOW = 33,
    Linemode = 34,
    XDISPLOC = 35,
    Environment = 36,
    Authentication = 37,
    Encryption = 38,
    NewEnvironment = 39,
    MSSP = 70,
    Compress = 85,
    Compress2 = 86,
    ZMP = 93,
    EXOPL = 255
}

pub struct TelnetOption {
    option_type: TelnetOptionType,
    us: bool,
    him: bool
}
